"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
dsfdsfdsf
sdfds
999.100.10
kk.kk.99
ddd
iiii
APP = ['main.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
